name: Warren Sander
favicon: null
layout_spectrum: 0.8691065881866962
typography_spectrum: 0.13845302793197334
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.011149193393066525
  lightness: 0.5800232694018632
  saturation: 0.6553835405502468
  rhythmicContrast: 0.9250174083281308
purpose: []
